### ISSUE TITLE
Several problems with Java 17

### ISSUE THREAD

**Issue by amseager** [schemacrawler/SchemaCrawler-Report-Maven-Plugin#13]
1. Seems like the graal-js dependency for graphviz  (https://github.com/nidi3/graphviz-java#maven) is now mandatory. I didn't manage to make SchemaCrawler plugin work with J2V8.
2. If you bind the plugin execution to any of the default maven phases (e.g. prepare-package), it'll stop work too because of doxia errors. Can be fixed by updating `doxia-site-renderer` to the never version (I've tested with 1.10 while in SchemaCrawler plugin it's 1.7 atm).

**Comment by sualeh** [comment]
@amseager - I don't see that these changes are needed in the SchemaCrawler Maven plugin itself - they would be in the pom.xml of the project that uses the plugin. If you disagree, I will open up this project to contributions, and request you for a pull request.

**Comment by amseager** [comment]
Thanks for the answer. I just wanted to highlight these things, and it's definitely possible to solve it by adding the required dependencies manually (that's what I did before reporting on this issue). So I think it's up to you to decide if it needs to be added to the project or not.

**Comment by sualeh** [comment]
Thanks, @amseager! Please submit a corresponding pull request to https://github.com/schemacrawler/SchemaCrawler-Report-Maven-Plugin-Usage-Example
