### ISSUE TITLE
Please update the plug-in to work with a current SchemaCrawler version

### ISSUE THREAD

**Issue by abstratt** [schemacrawler/SchemaCrawler-Report-Maven-Plugin#3]
I was struggling with getting the SchemaCrawler report plugin to accept customization of the Graphviz dot file generation, until I realized the plug-in uses an older version of SchemaCrawler itself.

Please update the plug-in to align with a more recent SchemaCrawler version, ideally with the latest one. Ideally, it would be great if version X.Y.Z of the plug-in depended on version X.Y.Z of SchemaCrawler, or at least some X.Y.*.

**Comment by abstratt** [comment]
Some context: I am trying to use SchemaCrawler to produce always up-to-date database schema documentation by running the SC's Maven report plug-in as part of a Jenkins build plan that runs every night, against a matrix of 6 database environments and 7 application schemas (it is a microservice-based architecture, each environment has the same multiple schemas).

**Comment by abstratt** [comment]
Thank you @sualeh! Looking forward to using the next release containing this fix. Do you have an idea of when it should be available (from Central)?

**Comment by sualeh** [comment]
@abstratt - please use the latest release, v14.21.02.01 and see if it works for you.
