### ISSUE TITLE
DiagramOptions Aren't Working

### ISSUE THREAD

**Issue by allan-shoup** [schemacrawler/SchemaCrawler-Report-Maven-Plugin#8]
I'm trying to set `schemacrawler.graph.show.foreignkey.cardinality=false` in a custom `config.properties` file and it doesn't seem to be having any effect.

Looking at the code it appears to be set in [DiagramRenderer.setDiagramOptions](https://github.com/schemacrawler/SchemaCrawler/blob/v16.9.4/schemacrawler-diagram/src/main/java/schemacrawler/tools/integration/diagram/DiagramRenderer.java#L157-L161), but I don't see that being called anywhere.

**Comment by sualeh** [comment]
@allan-shoup -  I am moving issue to the Maven plugin project.

**Comment by sualeh** [comment]
@allan-shoup - please use SchemaCrawler Report Maven Plugin version 16.9.4-2.

**Comment by allan-shoup** [comment]
Confirmed this is working with 16.9.4-2. Thank you for the quick turnaround.
