### ISSUE TITLE
Load row count option not settable from config file

### ISSUE THREAD

**Issue by allan-shoup** [schemacrawler/SchemaCrawler-Report-Maven-Plugin#9]
Setting `schemacrawler.format.show_row_counts=true` in the custom config file doesn't seem to be having an effect.

Does [LoadOptionsBulider.fromConfig](https://github.com/schemacrawler/SchemaCrawler/blob/v16.9.4/schemacrawler-api/src/main/java/schemacrawler/schemacrawler/LoadOptionsBuilder.java#L64-L77) need to set `isLoadRowCounts`?

**Comment by sualeh** [comment]
Exposes "loadrowcounts" configuration property in SchemaCrawler Report Maven Plugin. This will be available in the next release.

**Comment by sualeh** [comment]
@allan-shoup - please use SchemaCrawler Report Maven Plugin version 16.9.4-2.

**Comment by allan-shoup** [comment]
Confirmed 16.9.4-2 works perfectly. Thank you.
